# To run your pipeline on a Windows machine, create a self-hosted Windows runner.
# For instructions on setting up a Windows runner, see https://support.atlassian.com/bitbucket-cloud/docs/set-up-runners-for-windows/x

image: mcr.microsoft.com/dotnet/sdk:6.0

pipelines:
  branches:
    master:
        - step:
            name: Run unit tests
            caches:
              - dotnetcore
            script:
              - export SOLUTION_NAME=c-backtest-template
              - dotnet test --no-build
            artifacts:
              - test-reports/**
