#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, move this file to ./.git/hooks/pre-commit

dotnet build c-backtest-template.csproj
dotnet build TransformationTests/UnitTests.csproj
dotnet test TransformationTests/bin/Debug/net6.0/UnitTests.dll


git add -f bin/Debug/c-backtest-template.dll
git add -f TransformationTests/bin/Debug/net6.0/UnitTests.dll
git commit --amend -C HEAD --no-verify
